import React from 'react';
import { Link } from 'react-router-dom';
import { Leaf, Calculator, TrendingUp, Globe, Zap, Users } from 'lucide-react';

const Home = () => {
    return (
        <div>
            {/* Hero Section */}
            <section className="hero-section">
                <div className="container">
                    <h1 className="hero-title">
                        Calculate Your Carbon Footprint
                    </h1>
                    <p className="hero-subtitle">
                        Understand your environmental impact and discover personalized ways to reduce your carbon emissions for a sustainable future.
                    </p>
                    <Link to="/calculator" className="btn btn-primary">
                        <Calculator size={20} style={{ marginRight: '8px' }} />
                        Calculate Now
                    </Link>
                </div>
            </section>

            {/* Features Section */}
            <section className="features-section">
                <div className="container">
                    <div className="text-center">
                        <h2 className="info-title">Why Carbon Footprint Matters</h2>
                        <p className="info-text">
                            Your carbon footprint represents the total greenhouse gas emissions caused by your daily activities.
                            Understanding it is the first step towards making sustainable choices.
                        </p>
                    </div>

                    <div className="features-grid">
                        <div className="feature-card">
                            <div className="feature-icon">
                                <Globe size={40} />
                            </div>
                            <h3 className="feature-title">Environmental Impact</h3>
                            <p className="feature-description">
                                Every action we take has an environmental cost. Understanding your carbon footprint helps you make informed decisions about your lifestyle choices.
                            </p>
                        </div>

                        <div className="feature-card">
                            <div className="feature-icon">
                                <TrendingUp size={40} />
                            </div>
                            <h3 className="feature-title">Climate Change</h3>
                            <p className="feature-description">
                                Carbon emissions are the primary driver of climate change. Reducing your footprint contributes to global efforts to combat this crisis.
                            </p>
                        </div>

                        <div className="feature-card">
                            <div className="feature-icon">
                                <Users size={40} />
                            </div>
                            <h3 className="feature-title">Collective Action</h3>
                            <p className="feature-description">
                                Individual actions add up. When we all make sustainable choices, we create significant positive impact on our planet.
                            </p>
                        </div>
                    </div>
                </div>
            </section>

            {/* Info Section */}
            <section className="info-section">
                <div className="container">
                    <div className="info-content">
                        <h2 className="info-title">What is a Carbon Footprint?</h2>
                        <p className="info-text">
                            A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane)
                            that are generated by our actions. It's measured in units of carbon dioxide equivalents (CO2e).
                        </p>

                        <div className="stats-grid">
                            <div className="stat-card">
                                <div className="stat-number text-green">16.5</div>
                                <div className="stat-label">Tons CO2/year</div>
                                <div className="stat-label">Average US Citizen</div>
                            </div>

                            <div className="stat-card">
                                <div className="stat-number text-blue">2.0</div>
                                <div className="stat-label">Tons CO2/year</div>
                                <div className="stat-label">Sustainable Target</div>
                            </div>

                            <div className="stat-card">
                                <div className="stat-number text-orange">50%</div>
                                <div className="stat-label">Reduction Needed</div>
                                <div className="stat-label">By 2030</div>
                            </div>

                            <div className="stat-card">
                                <div className="stat-number text-red">1.5°C</div>
                                <div className="stat-label">Temperature Rise</div>
                                <div className="stat-label">Critical Limit</div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            {/* CTA Section */}
            <section style={{
                padding: '80px 0',
                background: 'linear-gradient(135deg, #10b981 0%, #059669 100%)',
                color: 'white',
                textAlign: 'center'
            }}>
                <div className="container">
                    <h2 style={{ fontSize: '2.5rem', fontWeight: '700', marginBottom: '24px' }}>
                        Ready to Make a Difference?
                    </h2>
                    <p style={{ fontSize: '1.1rem', marginBottom: '40px', opacity: '0.9', maxWidth: '600px', margin: '0 auto 40px' }}>
                        Calculate your carbon footprint in just a few minutes and get personalized recommendations to reduce your environmental impact.
                    </p>
                    <Link to="/calculator" className="btn" style={{
                        background: 'white',
                        color: '#10b981',
                        fontSize: '1.1rem',
                        padding: '16px 32px'
                    }}>
                        <Calculator size={20} style={{ marginRight: '8px' }} />
                        Start Calculating
                    </Link>
                </div>
            </section>
        </div>
    );
};

export default Home; 